spring.application.name=leave-service

server.port=8087

# =========================
# Eureka Configuration
# =========================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# =========================
# PostgreSQL Configuration
# =========================
spring.datasource.url=jdbc:postgresql://postgres:5432/lms_leave
spring.datasource.username=postgres
spring.datasource.password=K@rthikms@2
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA Configuration
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect (optional in Spring Boot 3)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# Spring Security
# =========================
spring.security.user.name=admin
spring.security.user.password=A@dmin9110