spring.application.name=leave-service
server.port=8087

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/lms_leave
spring.datasource.username=postgres
spring.datasource.password=K@rthikms@2
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=MyVerySecretKeyForLeaveManagementSystemSpringBootProject2026
jwt.expiration=86400000

# Kafka
spring.kafka.bootstrap-servers=kafka:29092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false